### ISSUE TITLE
f is not a function

### ISSUE THREAD

**Issue by RustyDev** [pcassis/angular-sticky-box#2]
Thank you for this awesome directive. We were chasing an error in our app `f is not a function` and tracked it down to this timeout during resize:

https://github.com/pcassis/angular-sticky-box/blob/master/src/angular-sticky-box.js#L153-L155

I opened a pull request for the fix. #1

**Comment by pcassis** [comment]
Thank you for this fix. Sorry it took so long...

**Comment by RustyDev** [comment]
Can you bump with version in bower?

**Comment by RustyDev** [comment]
Bumped the version and rebuilt the dist https://github.com/pcassis/angular-sticky-box/pull/5

**Comment by pcassis** [comment]
Done. thx
