### ISSUE TITLE
Doesn't work with dynamic content

### ISSUE THREAD

**Issue by dlorenzo** [pcassis/angular-sticky-box#3]
Hi,

When applied to elements that change height/content after page load, a window resize event is needed. Changing scroll() to setup() on("scroll") fixes the issue.  It could probably be optimized further but it works as a quick fix.

Made a fork with this fix attached: https://github.com/d-lorenzo/angular-sticky-box

Thanks!

**Comment by pcassis** [comment]
Sorry for delayed response... Could you make a pull request with your changes?

**Comment by dlorenzo** [comment]
Done. Thanks.

**Comment by pcassis** [comment]
Setup shouldn't be called on scroll event. Better solution is to emit "stickyBoxUpdate" event after your content is updated. Directive make setup when receive this event.

**Comment by dlorenzo** [comment]
I know it's not the most elegant or optimized solution but it was the only one at the time to make it compatible with AngularJS in a reasonable timeframe as, technically, all content is dynamic.
